 const UserActionTypes = {
        GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    CHECK_USER_SEASION: 'CHECK_USER_SEASION'
  };

  export default UserActionTypes;